[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "expenvelope"
version = "0.8.0"
description = "Piecewise-exponential curves designed for musical expressiveness."
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-3.0-only"

authors = [
    { name = "Marc Evanstein", email = "marc@marcevanstein.com" }
]

[project.urls]
"Source Code" = "https://github.com/MarcTheSpark/expenvelope"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
